---
- name: Install common packages
  yum: "name={{item}} state=present"
  with_items:
    - vim
    - wget
    - figlet
    - update-motd
    - glances
    - python-pip
    - python34-pip
    - python-passlib
    - curl
    - man-db
    - htop
    - openssh-server
    - tree
    - ncdu
    - dialog
    - lsof
    - pwgen
  ignore_errors: yes

- name: Pip Modes
  pip: "name={{item}} state=latest"
  with_items:
    - docker-py

- name: Ansible-ToolBox from https://github.com/larsks/ansible-toolbox
  shell: pip install git+https://github.com/larsks/ansible-toolbox
  ignore_errors: yes

- name: Remove Symbolic if it exists
  shell: unlink /etc/ansible/roles
  ignore_errors: yes

- name: Removing A Folder
  file:
    state: absent
    path: /etc/ansible/roles
  ignore_errors: yes

- name: Create Symbolic Link for Ansible-ToolBox
  shell: ln -s /opt/rdisco/ansible/roles /etc/ansible/
  ignore_errors: yes
