---
- name: LibreNMS Container
  docker_container:
    name: librenms
    state: absent

- name: Create LibreNMS directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/librenms/logs
    - /opt/appdata/librenms/rrd
    - /opt/appdata/librenms/ssl

- name: Deploy LibreNMS Container
  docker_container:
    name: librenms
    image: jarischaefer/docker-librenms
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}80:80"
      - "{{ports.stdout}}443:443"
    env:
      PUID: "1000"
      PGID: "1000"
      DB_HOST: "db"
      DB_NAME: "librenms"
      DB_USER: "librenms"
      DB_PASS: "secret"
      BASE_URL: "https://localhost"
      POLLERS: 16
      TZ: "PDT"
    volumes:
     - /opt/appdata/librenms/logs:/opt/librenms/logs
     - /opt/appdata/librenms/rrd:/opt/librenms/rrd
     - /opt/appdata/librenms/ssl:/etc/nginx/ssl:ro
    links:
      mariadb:db
    networks:
      - name: rdisco
        aliases:
          - librenms
    restart_policy: always
    state: started