---
- include_role:
    name: variables

- name: create rdisco network
  docker_network:
    name: "rdisco"
    state: present
    
- name: Portainer Container
  docker_container:
    name: portainer
    state: absent

- name: Create portainer directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/portainer

- name: Deploy Portainer Container
  docker_container:
    name: portainer
    image: portainer/portainer
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}9000:9000"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
     - /opt/appdata/portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
     - /opt/appdata/portainer:/data
    networks:
      - name: rdisco
        aliases:
          - portainer
    restart_policy: always
    state: started