---
- hosts: localhost

  roles:
  - { role: docker, tags: ['docker'] }
  - { role: librenms, tags: ['librenms'] }
  - { role: mariadb, tags: ['mariadb'] }
  - { role: motd, tags: ['motd'] }
  - { role: portainer, tags: ['portainer'] }
  - { role: preinstall, tags: ['preinstall'] }
  - { role: watchtower, tags: ['watchtower'] }