---
- name: Remove Watchtower Container
  docker_container:
    name: watchtower
    state: absent
- name: Deploy Watchtower (All)
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    pull: yes
    cpu_shares: 64
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    networks:
      - name: rdisco
        aliases:
          - watchtower
  tags: watchall